# NumPy Basics

A hands-on introduction to NumPy covering:
- Array creation
- Indexing & slicing
- Array operations
- Reshaping
- Aggregation functions (`sum`, `mean`, `min`, `max`)
- Boolean logic (`any`, `all`)

In [ ]:
import numpy as np

## 1. Array Creation

In [ ]:
# 2D array from a nested list
arr2 = np.array([[1, 2, 3, 4],
                 [4, 5, 6, 7],
                 [7, 8, 9, 10]])
print(arr2)

In [ ]:
# Number of dimensions and shape
print("ndim :", arr2.ndim)   # 2 — it's a 2D array
print("shape:", arr2.shape)  # (3, 4) — 3 rows, 4 columns

In [ ]:
# np.arange(start, stop) — stop is exclusive
arr3 = np.arange(1, 5)
print(arr3)  # [1 2 3 4]

In [ ]:
# np.arange(start, stop, step)
arr3 = np.arange(1, 5, 2)
print(arr3)  # [1 3]

In [ ]:
# Mixed int/float → NumPy upcasts to float64
ab = np.array([1, 2, 3.5, 6])
print(ab)           # [1.  2.  3.5 6. ]
print(ab.dtype)     # float64

In [ ]:
# Force integer dtype — 3.5 is truncated to 3
ab_int = np.array([1, 2, 3.5, 6], dtype="int")
print(ab_int)  # [1 2 3 6]

## 2. Indexing & Slicing

In [ ]:
arr = np.arange(1, 11)
print(arr)  # [ 1  2  3  4  5  6  7  8  9 10]

In [ ]:
# Positive and negative indexing
print(arr[0])   # 1  — first element
print(arr[1])   # 2
print(arr[-1])  # 10 — last element
print(arr[-2])  # 9  — second to last

In [ ]:
# Fancy indexing — pick elements by a list of indices
print(arr[[1, 4, 8, 3]])  # [2 5 9 4]

In [ ]:
# Slicing
print(arr[:5])    # [1 2 3 4 5]  — first 5
print(arr[-5:-1]) # [6 7 8 9]   — last 5, excluding the final element

# Note: arr[-5:-1:-1] returns empty [] because
# a negative step requires start > stop in negative-index terms.
# To reverse a slice, use arr[-1:-6:-1] instead.
print(arr[-1:-6:-1])  # [10  9  8  7  6]

## 3. Element-wise Operations

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a + b)         # [ 6  8 10 12]
print(np.add(a, b))  # [ 6  8 10 12]  — same as above
print(a * b)         # [ 5 12 21 32]
print(a + 10)        # [11 12 13 14]  — broadcasting a scalar
print(a ** 2)        # [ 1  4  9 16]

## 4. Reshaping Arrays

In [ ]:
# Reshape 12 elements → (6, 2)
a = np.arange(12).reshape(6, 2)
print(a)

In [ ]:
# reshape requires total elements to match: 15 ≠ 3×4=12
try:
    ab = np.arange(15).reshape(3, 4)
except ValueError as e:
    print(f"ValueError: {e}")

# Correct: 15 = 3×5
ab = np.arange(15).reshape(3, 5)
print(ab)

## 5. Aggregation: sum, mean, min, max

All aggregation functions accept an optional `axis` parameter:
- `axis=0` → collapse **rows** (operate down each column)
- `axis=1` → collapse **columns** (operate across each row)

In [ ]:
aa = np.arange(12).reshape(3, 4)
print(aa)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

In [ ]:
print(np.sum(aa))         # 66 — total of all elements
print(np.sum(aa, axis=0)) # [12 15 18 21] — column sums
print(np.sum(aa, axis=1)) # [ 6 22 38]    — row sums

In [ ]:
print(np.mean(aa))           # 5.5
# Manual verification:
print(np.sum(aa) / aa.size)  # 5.5

print(np.mean(aa, axis=0))   # [4. 5. 6. 7.]  — column means
print(np.mean(aa, axis=1))   # [1.5 5.5 9.5]  — row means

In [ ]:
print(np.min(aa))            # 0
print(np.min(aa, axis=0))    # [0 1 2 3]  — column minimums
print(np.min(aa, axis=1))    # [0 4 8]    — row minimums

print(np.max(aa))            # 11
print(np.max(aa, axis=0))    # [ 8  9 10 11]  — column maximums
print(np.max(aa, axis=1))    # [ 3  7 11]     — row maximums

## 6. Boolean Logic: any and all

- `np.any(cond)` → `True` if **at least one** element satisfies the condition
- `np.all(cond)` → `True` if **every** element satisfies the condition

In [ ]:
print(np.any(np.array([1, 2, 3, 4, 5, 6])))  # True  — non-zero values are truthy
print(np.any(np.array([0, 0, 0, 0, 0])))      # False — all zeros
print(np.any(np.array([1, 0, 0, 0, 0])))      # True  — at least one non-zero

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

print(np.any(a < b))   # True  — 1<4 and 2<3 satisfy the condition

a = np.array([5, 6, 7, 8])
print(np.any(a < b))   # False — every element of a is greater than b

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

print(np.all(a < b))   # False — not ALL elements of a are less than b

In [ ]:
# Chained comparison: check a <= b <= c element-wise
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

result = ((a <= b) & (b <= c)).all()
print(result)  # True