# NumPy Fundamentals

A hands-on walkthrough of **NumPy**, Python's core library for fast, vectorized numerical computing with arrays and matrices.

**Topics covered:** array creation, array properties, math & aggregation, indexing & slicing, reshaping & manipulation, broadcasting & vectorization, and handling missing values.

## Table of Contents
1. [Setup](#Setup)
2. [Creating Arrays](#Creating-Arrays)
3. [Array Properties & Operations](#Array-Properties-&-Operations)
4. [Mathematical Operations](#Mathematical-Operations)
5. [Aggregation Functions](#Aggregation-Functions)
6. [Indexing & Slicing](#Indexing-&-Slicing)
7. [Reshaping & Flattening](#Reshaping-&-Flattening)
8. [Adding, Removing & Combining Elements](#Adding,-Removing-&-Combining-Elements)
9. [Stacking & Splitting](#Stacking-&-Splitting)
10. [Broadcasting & Vectorization](#Broadcasting-&-Vectorization)
11. [Handling Missing Values](#Handling-Missing-Values)

---

## Setup
NumPy must be imported before use, and it's conventionally aliased as `np`.

In [1]:
import numpy as np

## Creating Arrays
A NumPy array (`ndarray`) is a grid-like container for numerical data that supports fast, vectorized operations, unlike plain Python lists.

*A simple one-dimensional array created from a Python list.*

In [3]:
temp = np.array([21.4,34.6,54.6,11.6,20.5])
print(temp)

[21.4 34.6 54.6 11.6 20.5]


*A two-dimensional array (matrix) built from nested lists.*

In [4]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
matrix = np.array([[2,4,6],[8,10,12]])
print(matrix)

[[ 2  4  6]
 [ 8 10 12]]


*`np.arange` generates a sequence of numbers; slicing with `[::-1]` reverses it.*

In [10]:
arr = np.arange(1,11)[::-1]
print(arr)

[10  9  8  7  6  5  4  3  2  1]


*Quick ways to create pre-filled arrays: all zeros, all ones, a constant value, and an identity matrix.*

In [11]:
arr1 = np.zeros(3)
print(arr1)

[0. 0. 0.]


In [13]:
arr1 = np.ones((2,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
arr2 = np.full((2,3),7)
print(arr2)

[[7 7 7]
 [7 7 7]]


In [16]:
id_matrix = np.eye(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Array Properties & Operations
Once created, arrays expose attributes and methods to inspect their structure and convert their data type.

*`.shape` returns the dimensions (rows, columns) of an array.*

In [18]:
# shape

arr_2d = np.array([[1,2,3],[4,5,6]]).shape

print(arr_2d)

(2, 3)


*`.size` returns the total number of elements in an array.*

In [23]:
# size

arr3 = np.array([[1,2,3,4],[5,6,7,8]]).size

print(arr3)

8


*`.ndim` returns the number of dimensions (axes) of an array.*

In [28]:
# ndim

arr4 = np.array([[1,2,3],[2,3,4]]).ndim
arr5 = np.array([[[1,2,3],[2,3,4],[5,6,7],[9,10,11]]]).ndim

print(arr4)
print(arr5)

2
3


*`.dtype` returns the data type of the array's elements.*

In [31]:
# dtype

arr = np.array([1,2,3]).dtype

print(arr)

int64


*`.astype()` converts an array's elements to a different data type.*

In [34]:
# astype

arr = np.array(['100','101','102','103','104','105']).astype('int')

print(arr)

[100 101 102 103 104 105]


## Mathematical Operations
NumPy supports element-wise arithmetic (`+ - * / ** // %`) directly on arrays, without writing explicit loops.

In [38]:
# Mathematical Operations
# + , - , * , / , ** , // , %

arr = np.array([10,20,30,40,50])+5
arr1 = np.array([10,20,30,40,50])*2
arr2 = np.array([10,20,30,40,50])**2

print(arr)
print(arr1)
print(arr2)

[15 25 35 45 55]
[ 20  40  60  80 100]
[ 100  400  900 1600 2500]


## Aggregation Functions
Aggregation functions summarize an array's data into a single statistic, such as sum, mean, or standard deviation.

In [47]:
arr = np.array([12,34,56,67,78,89])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

336
56.0
12
89
26.185237571323782
685.6666666666666


## Indexing & Slicing
Indexing and slicing let you access individual elements or sub-sections of an array.

*Access a single element by its index position.*

In [52]:
arr = np.array([10,20,30,40,50,60,70])

print(arr[0])
print(arr[2])

10
30


*Slice a range of elements using `start:stop`.*

In [55]:
arr = np.array([10,20,30,40,50,60,70])

print(arr[:2])



[10 20]
[10 20 30 40 50 60 70]


*Fancy indexing: select multiple specific elements using a list of indices.*

In [56]:
arr = np.array([10,20,30,40,50,60,70])

print(arr[[0,2,4]])

[10 30 50]


*Boolean masking filters elements based on a condition.*

In [57]:
# Boolean Masking

arr = np.array([10,20,30,40,50,60,70])

print(arr[arr > 25])

[30 40 50 60 70]


## Reshaping & Flattening
Reshaping changes an array's dimensions without changing its underlying data.

*`.reshape()` rearranges an array into new dimensions (same total number of elements).*

In [62]:
arr = np.array([10,20,30,40,50,60,70,80,90])

new_arr = arr.reshape(3,3)

print(new_arr)
print(arr)




[[10 20 30]
 [40 50 60]
 [70 80 90]]
[10 20 30 40 50 60 70 80 90]


*Flattening converts a multi-dimensional array into 1D: `.flatten()` returns a copy, `.ravel()` returns a view where possible.*

In [69]:
# Flattening array

arr5 = np.array([[[1,2,3],[2,3,4],[5,6,7],[9,10,11]]])

print(arr5.flatten())  # copy
print(arr5.ravel())    # view
print(arr5)

[ 1  2  3  2  3  4  5  6  7  9 10 11]
[ 1  2  3  2  3  4  5  6  7  9 10 11]
[[[ 1  2  3]
  [ 2  3  4]
  [ 5  6  7]
  [ 9 10 11]]]


## Adding, Removing & Combining Elements
NumPy provides functions to insert, append, concatenate, or delete elements from an array.

*`np.insert` adds a value at a specific position along an axis.*

In [71]:
arr = np.array([10,20,30,40,50,60,70,80,90])

new_arr = np.insert(arr,2,100,axis=0)

print(new_arr)
print(arr)

[ 10  20 100  30  40  50  60  70  80  90]
[10 20 30 40 50 60 70 80 90]


*Inserting a new column into a 2D array using `axis=1`.*

In [80]:
arr_2d = np.array([[1,2,3],[2,3,4],[5,6,7],[9,10,11]])
arr_2d

new_arr = np.insert(arr_2d,1,[5,6,8,9],axis = 1)
new_arr

array([[ 1,  5,  2,  3],
       [ 2,  6,  3,  4],
       [ 5,  8,  6,  7],
       [ 9,  9, 10, 11]])

*`np.append` adds elements to the end of an array.*

In [83]:
arr = np.array([10,20,30,40,50,60,70,80,90])

new_arr = np.append(arr,777)

print(new_arr)

[ 10  20  30  40  50  60  70  80  90 777]


*`np.concatenate` joins two or more arrays into one.*

In [88]:
a = np.array([1,2,3])
b = np.array([5,6,7])

c = np.concatenate((a,b))

print(c)

[1 2 3 5 6 7]


*`np.delete` removes elements at the given index/indices.*

In [91]:
arr = np.array([10,20,30,40,50,60,70,80,90])

new_arr = np.delete(arr,1)

print(new_arr)

[10 30 40 50 60 70 80 90]


*Deleting a column from a 2D array using `axis=1`.*

In [93]:
arr_2d = np.array([[1,2,3],[2,3,4],[5,6,7],[9,10,11]])

new_arr = np.delete(arr_2d,1, axis = 1)

print(new_arr)

[[ 1  3]
 [ 2  4]
 [ 5  7]
 [ 9 11]]


## Stacking & Splitting
Stacking combines arrays along a new axis, while splitting breaks one array into multiple smaller arrays.

*`np.vstack` stacks arrays vertically (row-wise); `np.hstack` stacks them horizontally (column-wise).*

In [100]:
a = np.array([1,2,3])
b = np.array([5,6,7])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [5 6 7]]
[1 2 3 5 6 7]


*`np.split` divides an array into equal-sized sub-arrays.*

In [106]:
arr = np.array([10,20,30,40,50,60,70,80,90])

print(np.split(arr,3))

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]


## Broadcasting & Vectorization
Broadcasting lets NumPy operate on arrays of different shapes by automatically expanding the smaller one, while vectorization replaces explicit loops with fast, array-wise operations.

*A practical example: applying a scalar discount to an entire price array at once.*

In [107]:
prices = np.array([100,200,300,400])
discount = 10

final_prices = prices - (prices * discount / 100)

print(final_prices)

[ 90. 180. 270. 360.]


*Broadcasting rules in action: matching shapes, expanding a scalar, and the error raised when shapes are incompatible.*

In [ ]:
# Matching Dimenssions

a = np.array([1,2,3])
b = np.array([5,6,7])

print(a+b) 


# Expanding single elements

a = np.array([1,2,3])

print(a + 10)


# Incompatible Shapes

a = np.array([1,2,3])
b = np.array([5,6])

print(a+b)  #Error


[ 6  8 10]
[11 12 13]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

### Vectorized Operations
Vectorized operations apply a calculation to every element simultaneously, avoiding slow Python `for` loops.

In [113]:
a = np.array([1,2,3])
b = np.array([5,6,7])


result = a + b

print(result)

aa = np.array([1,2,3])
multiplied = aa * 4
print(multiplied)



[ 6  8 10]
[ 4  8 12]


## Handling Missing Values
Real-world data often contains missing (`NaN`) or infinite values; NumPy provides tools to detect and clean them.

*`np.isnan` returns a boolean mask marking which elements are `NaN`.*

In [114]:
arr = np.array([1,2,np.nan,4,np.nan,6])

print(np.isnan(arr))

[False False  True False  True False]


*`np.nan_to_num` replaces `NaN` values with a specified number.*

In [117]:
arr = np.array([1,2,np.nan,4,np.nan,6])

print(np.nan_to_num(arr, nan = 10))

[ 1.  2. 10.  4. 10.  6.]


*`np.isinf` returns a boolean mask marking which elements are infinite (`inf` or `-inf`).*

In [118]:
arr = np.array([1,2,np.inf,4,-np.inf,6])

print(np.isinf(arr))

[False False  True False  True False]


*The same function can also replace positive and negative infinity with custom values.*

In [119]:
arr = np.array([1,2,np.inf,4,-np.inf,6])

cleaned_arr = np.nan_to_num(arr, posinf = 1000, neginf = -1000)

print(cleaned_arr)

[    1.     2.  1000.     4. -1000.     6.]
